[package]
name = "tc_ui"
version = "0.2.1"
edition = "2024"

[lib]
name = "tc_ui"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module"] }

[package-metadata.maturin]
include-pyi = true
