class HtmlElement:
    def __init__(self, style: StyleComponent, id: str) -> None:
        self.style: StyleComponent = style
        self.id: str = id


    def content(self, *e) -> None: ...

class Colors:
    ...


class StyleComponent:
    def __init__(self) -> None:
        self.properties: dict

    def set_property(self, value: str) -> 'StyleComponent': ...

    def set_align_content(self, value: str) -> 'StyleComponent': ...

    def set_align_items(self, value: str) -> 'StyleComponent': ...

    def set_align_self(self, value: str) -> 'StyleComponent': ...

    def set_alignment_adjust(self, value: str) -> 'StyleComponent': ...

    def set_alignment_baseline(self, value: str) -> 'StyleComponent': ...

    def set_all(self, value: str) -> 'StyleComponent': ...

    def set_alt(self, value: str) -> 'StyleComponent': ...

    def set_animation(self, value: str) -> 'StyleComponent': ...

    def set_animation_delay(self, value: str) -> 'StyleComponent': ...

    def set_animation_direction(self, value: str) -> 'StyleComponent': ...

    def set_animation_duration(self, value: str) -> 'StyleComponent': ...

    def set_animation_fill_mode(self, value: str) -> 'StyleComponent': ...

    def set_animation_iteration_count(self, value: str) -> 'StyleComponent': ...

    def set_animation_name(self, value: str) -> 'StyleComponent': ...

    def set_animation_play_state(self, value: str) -> 'StyleComponent': ...

    def set_animation_timing_function(self, value: str) -> 'StyleComponent': ...

    def set_azimuth(self, value: str) -> 'StyleComponent': ...

    def set_backface_visibility(self, value: str) -> 'StyleComponent': ...

    def set_background(self, value: str) -> 'StyleComponent': ...

    def set_background_attachment(self, value: str) -> 'StyleComponent': ...

    def set_background_clip(self, value: str) -> 'StyleComponent': ...

    def set_background_color(self, value: str) -> 'StyleComponent': ...

    def set_background_image(self, value: str) -> 'StyleComponent': ...

    def set_background_origin(self, value: str) -> 'StyleComponent': ...

    def set_background_position(self, value: str) -> 'StyleComponent': ...

    def set_background_repeat(self, value: str) -> 'StyleComponent': ...

    def set_background_size(self, value: str) -> 'StyleComponent': ...

    def set_background_blend_mode(self, value: str) -> 'StyleComponent': ...

    def set_baseline_shift(self, value: str) -> 'StyleComponent': ...

    def set_bleed(self, value: str) -> 'StyleComponent': ...

    def set_bookmark_label(self, value: str) -> 'StyleComponent': ...

    def set_bookmark_level(self, value: str) -> 'StyleComponent': ...

    def set_bookmark_state(self, value: str) -> 'StyleComponent': ...

    def set_border(self, value: str) -> 'StyleComponent': ...

    def set_border_color(self, value: str) -> 'StyleComponent': ...

    def set_border_style(self, value: str) -> 'StyleComponent': ...

    def set_border_width(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom_color(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom_style(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom_width(self, value: str) -> 'StyleComponent': ...

    def set_border_left(self, value: str) -> 'StyleComponent': ...

    def set_border_left_color(self, value: str) -> 'StyleComponent': ...

    def set_border_left_style(self, value: str) -> 'StyleComponent': ...

    def set_border_left_width(self, value: str) -> 'StyleComponent': ...

    def set_border_right(self, value: str) -> 'StyleComponent': ...

    def set_border_right_color(self, value: str) -> 'StyleComponent': ...

    def set_border_right_style(self, value: str) -> 'StyleComponent': ...

    def set_border_right_width(self, value: str) -> 'StyleComponent': ...

    def set_border_top(self, value: str) -> 'StyleComponent': ...

    def set_border_top_color(self, value: str) -> 'StyleComponent': ...

    def set_border_top_style(self, value: str) -> 'StyleComponent': ...

    def set_border_top_width(self, value: str) -> 'StyleComponent': ...

    def set_border_collapse(self, value: str) -> 'StyleComponent': ...

    def set_border_image(self, value: str) -> 'StyleComponent': ...

    def set_border_image_outset(self, value: str) -> 'StyleComponent': ...

    def set_border_image_repeat(self, value: str) -> 'StyleComponent': ...

    def set_border_image_slice(self, value: str) -> 'StyleComponent': ...

    def set_border_image_source(self, value: str) -> 'StyleComponent': ...

    def set_border_image_width(self, value: str) -> 'StyleComponent': ...

    def set_border_radius(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom_left_radius(self, value: str) -> 'StyleComponent': ...

    def set_border_bottom_right_radius(self, value: str) -> 'StyleComponent': ...

    def set_border_top_left_radius(self, value: str) -> 'StyleComponent': ...

    def set_border_top_right_radius(self, value: str) -> 'StyleComponent': ...

    def set_border_spacing(self, value: str) -> 'StyleComponent': ...

    def set_bottom(self, value: str) -> 'StyleComponent': ...

    def set_box_decoration_break(self, value: str) -> 'StyleComponent': ...

    def set_box_shadow(self, value: str) -> 'StyleComponent': ...

    def set_box_sizing(self, value: str) -> 'StyleComponent': ...

    def set_box_snap(self, value: str) -> 'StyleComponent': ...

    def set_break_after(self, value: str) -> 'StyleComponent': ...

    def set_break_before(self, value: str) -> 'StyleComponent': ...

    def set_break_inside(self, value: str) -> 'StyleComponent': ...

    def set_buffered_rendering(self, value: str) -> 'StyleComponent': ...

    def set_caption_side(self, value: str) -> 'StyleComponent': ...

    def set_clear(self, value: str) -> 'StyleComponent': ...

    def set_clear_side(self, value: str) -> 'StyleComponent': ...

    def set_clip(self, value: str) -> 'StyleComponent': ...

    def set_clip_path(self, value: str) -> 'StyleComponent': ...

    def set_clip_rule(self, value: str) -> 'StyleComponent': ...

    def set_color(self, value: str) -> 'StyleComponent': ...

    def set_color_adjust(self, value: str) -> 'StyleComponent': ...

    def set_color_correction(self, value: str) -> 'StyleComponent': ...

    def set_color_interpolation(self, value: str) -> 'StyleComponent': ...

    def set_color_interpolation_filters(self, value: str) -> 'StyleComponent': ...

    def set_color_profile(self, value: str) -> 'StyleComponent': ...

    def set_color_rendering(self, value: str) -> 'StyleComponent': ...

    def set_column_fill(self, value: str) -> 'StyleComponent': ...

    def set_column_gap(self, value: str) -> 'StyleComponent': ...

    def set_column_rule(self, value: str) -> 'StyleComponent': ...

    def set_column_rule_color(self, value: str) -> 'StyleComponent': ...

    def set_column_rule_style(self, value: str) -> 'StyleComponent': ...

    def set_column_rule_width(self, value: str) -> 'StyleComponent': ...

    def set_column_span(self, value: str) -> 'StyleComponent': ...

    def set_columns(self, value: str) -> 'StyleComponent': ...

    def set_column_count(self, value: str) -> 'StyleComponent': ...

    def set_column_width(self, value: str) -> 'StyleComponent': ...

    def set_contain(self, value: str) -> 'StyleComponent': ...

    def set_content(self, value: str) -> 'StyleComponent': ...

    def set_counter_increment(self, value: str) -> 'StyleComponent': ...

    def set_counter_reset(self, value: str) -> 'StyleComponent': ...

    def set_counter_set(self, value: str) -> 'StyleComponent': ...

    def set_cue(self, value: str) -> 'StyleComponent': ...

    def set_cue_after(self, value: str) -> 'StyleComponent': ...

    def set_cue_before(self, value: str) -> 'StyleComponent': ...

    def set_cursor(self, value: str) -> 'StyleComponent': ...

    def set_direction(self, value: str) -> 'StyleComponent': ...

    def set_display(self, value: str) -> 'StyleComponent': ...

    def set_display_inside(self, value: str) -> 'StyleComponent': ...

    def set_display_outside(self, value: str) -> 'StyleComponent': ...

    def set_display_extras(self, value: str) -> 'StyleComponent': ...

    def set_display_box(self, value: str) -> 'StyleComponent': ...

    def set_dominant_baseline(self, value: str) -> 'StyleComponent': ...

    def set_elevation(self, value: str) -> 'StyleComponent': ...

    def set_empty_cells(self, value: str) -> 'StyleComponent': ...

    def set_enable_background(self, value: str) -> 'StyleComponent': ...

    def set_fill(self, value: str) -> 'StyleComponent': ...

    def set_fill_opacity(self, value: str) -> 'StyleComponent': ...

    def set_fill_rule(self, value: str) -> 'StyleComponent': ...

    def set_filter(self, value: str) -> 'StyleComponent': ...

    def set_float(self, value: str) -> 'StyleComponent': ...

    def set_float_defer_column(self, value: str) -> 'StyleComponent': ...

    def set_float_defer_page(self, value: str) -> 'StyleComponent': ...

    def set_float_offset(self, value: str) -> 'StyleComponent': ...

    def set_float_wrap(self, value: str) -> 'StyleComponent': ...

    def set_flow_into(self, value: str) -> 'StyleComponent': ...

    def set_flow_from(self, value: str) -> 'StyleComponent': ...

    def set_flex(self, value: str) -> 'StyleComponent': ...

    def set_flex_basis(self, value: str) -> 'StyleComponent': ...

    def set_flex_grow(self, value: str) -> 'StyleComponent': ...

    def set_flex_shrink(self, value: str) -> 'StyleComponent': ...

    def set_flex_flow(self, value: str) -> 'StyleComponent': ...

    def set_flex_direction(self, value: str) -> 'StyleComponent': ...

    def set_flex_wrap(self, value: str) -> 'StyleComponent': ...

    def set_flood_color(self, value: str) -> 'StyleComponent': ...

    def set_flood_opacity(self, value: str) -> 'StyleComponent': ...

    def set_font(self, value: str) -> 'StyleComponent': ...

    def set_font_family(self, value: str) -> 'StyleComponent': ...

    def set_font_size(self, value: str) -> 'StyleComponent': ...

    def set_font_stretch(self, value: str) -> 'StyleComponent': ...

    def set_font_style(self, value: str) -> 'StyleComponent': ...

    def set_font_weight(self, value: str) -> 'StyleComponent': ...

    def set_font_feature_settings(self, value: str) -> 'StyleComponent': ...

    def set_font_kerning(self, value: str) -> 'StyleComponent': ...

    def set_font_language_override(self, value: str) -> 'StyleComponent': ...

    def set_font_size_adjust(self, value: str) -> 'StyleComponent': ...

    def set_font_synthesis(self, value: str) -> 'StyleComponent': ...

    def set_font_variant(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_alternates(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_caps(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_east_asian(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_ligatures(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_numeric(self, value: str) -> 'StyleComponent': ...

    def set_font_variant_position(self, value: str) -> 'StyleComponent': ...

    def set_footnote_policy(self, value: str) -> 'StyleComponent': ...

    def set_glyph_orientation_horizontal(self, value: str) -> 'StyleComponent': ...

    def set_glyph_orientation_vertical(self, value: str) -> 'StyleComponent': ...

    def set_grid(self, value: str) -> 'StyleComponent': ...

    def set_grid_auto_flow(self, value: str) -> 'StyleComponent': ...

    def set_grid_auto_columns(self, value: str) -> 'StyleComponent': ...

    def set_grid_auto_rows(self, value: str) -> 'StyleComponent': ...

    def set_grid_template(self, value: str) -> 'StyleComponent': ...

    def set_grid_template_areas(self, value: str) -> 'StyleComponent': ...

    def set_grid_template_columns(self, value: str) -> 'StyleComponent': ...

    def set_grid_template_rows(self, value: str) -> 'StyleComponent': ...

    def set_grid_area(self, value: str) -> 'StyleComponent': ...

    def set_grid_column(self, value: str) -> 'StyleComponent': ...

    def set_grid_column_start(self, value: str) -> 'StyleComponent': ...

    def set_grid_column_end(self, value: str) -> 'StyleComponent': ...

    def set_grid_row(self, value: str) -> 'StyleComponent': ...

    def set_grid_row_start(self, value: str) -> 'StyleComponent': ...

    def set_grid_row_end(self, value: str) -> 'StyleComponent': ...

    def set_hanging_punctuation(self, value: str) -> 'StyleComponent': ...

    def set_height(self, value: str) -> 'StyleComponent': ...

    def set_hyphenate_character(self, value: str) -> 'StyleComponent': ...

    def set_hyphenate_limit_chars(self, value: str) -> 'StyleComponent': ...

    def set_hyphenate_limit_last(self, value: str) -> 'StyleComponent': ...

    def set_hyphenate_limit_lines(self, value: str) -> 'StyleComponent': ...

    def set_hyphenate_limit_zone(self, value: str) -> 'StyleComponent': ...

    def set_hyphens(self, value: str) -> 'StyleComponent': ...

    def set_icon(self, value: str) -> 'StyleComponent': ...

    def set_image_orientation(self, value: str) -> 'StyleComponent': ...

    def set_image_resolution(self, value: str) -> 'StyleComponent': ...

    def set_image_rendering(self, value: str) -> 'StyleComponent': ...

    def set_ime(self, value: str) -> 'StyleComponent': ...

    def set_ime_align(self, value: str) -> 'StyleComponent': ...

    def set_ime_mode(self, value: str) -> 'StyleComponent': ...

    def set_ime_offset(self, value: str) -> 'StyleComponent': ...

    def set_ime_width(self, value: str) -> 'StyleComponent': ...

    def set_initial_letters(self, value: str) -> 'StyleComponent': ...

    def set_inline_box_align(self, value: str) -> 'StyleComponent': ...

    def set_isolation(self, value: str) -> 'StyleComponent': ...

    def set_justify_content(self, value: str) -> 'StyleComponent': ...

    def set_justify_items(self, value: str) -> 'StyleComponent': ...

    def set_justify_self(self, value: str) -> 'StyleComponent': ...

    def set_kerning(self, value: str) -> 'StyleComponent': ...

    def set_left(self, value: str) -> 'StyleComponent': ...

    def set_letter_spacing(self, value: str) -> 'StyleComponent': ...

    def set_lighting_color(self, value: str) -> 'StyleComponent': ...

    def set_line_box_contain(self, value: str) -> 'StyleComponent': ...

    def set_line_break(self, value: str) -> 'StyleComponent': ...

    def set_line_grid(self, value: str) -> 'StyleComponent': ...

    def set_line_height(self, value: str) -> 'StyleComponent': ...

    def set_line_slack(self, value: str) -> 'StyleComponent': ...

    def set_line_snap(self, value: str) -> 'StyleComponent': ...

    def set_list_style(self, value: str) -> 'StyleComponent': ...

    def set_list_style_image(self, value: str) -> 'StyleComponent': ...

    def set_list_style_position(self, value: str) -> 'StyleComponent': ...

    def set_list_style_type(self, value: str) -> 'StyleComponent': ...

    def set_margin(self, value: str) -> 'StyleComponent': ...

    def set_margin_bottom(self, value: str) -> 'StyleComponent': ...

    def set_margin_left(self, value: str) -> 'StyleComponent': ...

    def set_margin_right(self, value: str) -> 'StyleComponent': ...

    def set_margin_top(self, value: str) -> 'StyleComponent': ...

    def set_marker(self, value: str) -> 'StyleComponent': ...

    def set_marker_end(self, value: str) -> 'StyleComponent': ...

    def set_marker_mid(self, value: str) -> 'StyleComponent': ...

    def set_marker_pattern(self, value: str) -> 'StyleComponent': ...

    def set_marker_segment(self, value: str) -> 'StyleComponent': ...

    def set_marker_start(self, value: str) -> 'StyleComponent': ...

    def set_marker_knockout_left(self, value: str) -> 'StyleComponent': ...

    def set_marker_knockout_right(self, value: str) -> 'StyleComponent': ...

    def set_marker_side(self, value: str) -> 'StyleComponent': ...

    def set_marks(self, value: str) -> 'StyleComponent': ...

    def set_marquee_direction(self, value: str) -> 'StyleComponent': ...

    def set_marquee_play_count(self, value: str) -> 'StyleComponent': ...

    def set_marquee_speed(self, value: str) -> 'StyleComponent': ...

    def set_marquee_style(self, value: str) -> 'StyleComponent': ...

    def set_mask(self, value: str) -> 'StyleComponent': ...

    def set_mask_image(self, value: str) -> 'StyleComponent': ...

    def set_mask_repeat(self, value: str) -> 'StyleComponent': ...

    def set_mask_position(self, value: str) -> 'StyleComponent': ...

    def set_mask_clip(self, value: str) -> 'StyleComponent': ...

    def set_mask_origin(self, value: str) -> 'StyleComponent': ...

    def set_mask_size(self, value: str) -> 'StyleComponent': ...

    def set_mask_box(self, value: str) -> 'StyleComponent': ...

    def set_mask_box_outset(self, value: str) -> 'StyleComponent': ...

    def set_mask_box_repeat(self, value: str) -> 'StyleComponent': ...

    def set_mask_box_slice(self, value: str) -> 'StyleComponent': ...

    def set_mask_box_source(self, value: str) -> 'StyleComponent': ...

    def set_mask_box_width(self, value: str) -> 'StyleComponent': ...

    def set_mask_type(self, value: str) -> 'StyleComponent': ...

    def set_max_height(self, value: str) -> 'StyleComponent': ...

    def set_max_lines(self, value: str) -> 'StyleComponent': ...

    def set_max_width(self, value: str) -> 'StyleComponent': ...

    def set_min_height(self, value: str) -> 'StyleComponent': ...

    def set_min_width(self, value: str) -> 'StyleComponent': ...

    def set_mix_blend_mode(self, value: str) -> 'StyleComponent': ...

    def set_nav_down(self, value: str) -> 'StyleComponent': ...

    def set_nav_index(self, value: str) -> 'StyleComponent': ...

    def set_nav_left(self, value: str) -> 'StyleComponent': ...

    def set_nav_right(self, value: str) -> 'StyleComponent': ...

    def set_nav_up(self, value: str) -> 'StyleComponent': ...

    def set_object_fit(self, value: str) -> 'StyleComponent': ...

    def set_object_position(self, value: str) -> 'StyleComponent': ...

    def set_offset_after(self, value: str) -> 'StyleComponent': ...

    def set_offset_before(self, value: str) -> 'StyleComponent': ...

    def set_offset_end(self, value: str) -> 'StyleComponent': ...

    def set_offset_start(self, value: str) -> 'StyleComponent': ...

    def set_opacity(self, value: str) -> 'StyleComponent': ...

    def set_order(self, value: str) -> 'StyleComponent': ...

    def set_orphans(self, value: str) -> 'StyleComponent': ...

    def set_outline(self, value: str) -> 'StyleComponent': ...

    def set_outline_color(self, value: str) -> 'StyleComponent': ...

    def set_outline_style(self, value: str) -> 'StyleComponent': ...

    def set_outline_width(self, value: str) -> 'StyleComponent': ...

    def set_outline_offset(self, value: str) -> 'StyleComponent': ...

    def set_overflow(self, value: str) -> 'StyleComponent': ...

    def set_overflow_x(self, value: str) -> 'StyleComponent': ...

    def set_overflow_y(self, value: str) -> 'StyleComponent': ...

    def set_overflow_style(self, value: str) -> 'StyleComponent': ...

    def set_overflow_wrap(self, value: str) -> 'StyleComponent': ...

    def set_padding(self, value: str) -> 'StyleComponent': ...

    def set_padding_bottom(self, value: str) -> 'StyleComponent': ...

    def set_padding_left(self, value: str) -> 'StyleComponent': ...

    def set_padding_right(self, value: str) -> 'StyleComponent': ...

    def set_padding_top(self, value: str) -> 'StyleComponent': ...

    def set_page(self, value: str) -> 'StyleComponent': ...

    def set_page_break_after(self, value: str) -> 'StyleComponent': ...

    def set_page_break_before(self, value: str) -> 'StyleComponent': ...

    def set_page_break_inside(self, value: str) -> 'StyleComponent': ...

    def set_paint_order(self, value: str) -> 'StyleComponent': ...

    def set_pause(self, value: str) -> 'StyleComponent': ...

    def set_pause_after(self, value: str) -> 'StyleComponent': ...

    def set_pause_before(self, value: str) -> 'StyleComponent': ...

    def set_perspective(self, value: str) -> 'StyleComponent': ...

    def set_perspective_origin(self, value: str) -> 'StyleComponent': ...

    def set_pitch(self, value: str) -> 'StyleComponent': ...

    def set_pitch_range(self, value: str) -> 'StyleComponent': ...

    def set_play_during(self, value: str) -> 'StyleComponent': ...

    def set_pointer_events(self, value: str) -> 'StyleComponent': ...

    def set_position(self, value: str) -> 'StyleComponent': ...

    def set_quotes(self, value: str) -> 'StyleComponent': ...

    def set_region_fragment(self, value: str) -> 'StyleComponent': ...

    def set_resize(self, value: str) -> 'StyleComponent': ...

    def set_rest(self, value: str) -> 'StyleComponent': ...

    def set_rest_after(self, value: str) -> 'StyleComponent': ...

    def set_rest_before(self, value: str) -> 'StyleComponent': ...

    def set_richness(self, value: str) -> 'StyleComponent': ...

    def set_right(self, value: str) -> 'StyleComponent': ...

    def set_ruby_align(self, value: str) -> 'StyleComponent': ...

    def set_ruby_merge(self, value: str) -> 'StyleComponent': ...

    def set_ruby_position(self, value: str) -> 'StyleComponent': ...

    def set_scroll_behavior(self, value: str) -> 'StyleComponent': ...

    def set_scroll_snap_coordinate(self, value: str) -> 'StyleComponent': ...

    def set_scroll_snap_destination(self, value: str) -> 'StyleComponent': ...

    def set_scroll_snap_points_x(self, value: str) -> 'StyleComponent': ...

    def set_scroll_snap_points_y(self, value: str) -> 'StyleComponent': ...

    def set_scroll_snap_type(self, value: str) -> 'StyleComponent': ...

    def set_shape_image_threshold(self, value: str) -> 'StyleComponent': ...

    def set_shape_inside(self, value: str) -> 'StyleComponent': ...

    def set_shape_margin(self, value: str) -> 'StyleComponent': ...

    def set_shape_outside(self, value: str) -> 'StyleComponent': ...

    def set_shape_padding(self, value: str) -> 'StyleComponent': ...

    def set_shape_rendering(self, value: str) -> 'StyleComponent': ...

    def set_size(self, value: str) -> 'StyleComponent': ...

    def set_speak(self, value: str) -> 'StyleComponent': ...

    def set_speak_as(self, value: str) -> 'StyleComponent': ...

    def set_speak_header(self, value: str) -> 'StyleComponent': ...

    def set_speak_numeral(self, value: str) -> 'StyleComponent': ...

    def set_speak_punctuation(self, value: str) -> 'StyleComponent': ...

    def set_speech_rate(self, value: str) -> 'StyleComponent': ...

    def set_stop_color(self, value: str) -> 'StyleComponent': ...

    def set_stop_opacity(self, value: str) -> 'StyleComponent': ...

    def set_stress(self, value: str) -> 'StyleComponent': ...

    def set_string_set(self, value: str) -> 'StyleComponent': ...

    def set_stroke(self, value: str) -> 'StyleComponent': ...

    def set_stroke_dasharray(self, value: str) -> 'StyleComponent': ...

    def set_stroke_dashoffset(self, value: str) -> 'StyleComponent': ...

    def set_stroke_linecap(self, value: str) -> 'StyleComponent': ...

    def set_stroke_linejoin(self, value: str) -> 'StyleComponent': ...

    def set_stroke_miterlimit(self, value: str) -> 'StyleComponent': ...

    def set_stroke_opacity(self, value: str) -> 'StyleComponent': ...

    def set_stroke_width(self, value: str) -> 'StyleComponent': ...

    def set_tab_size(self, value: str) -> 'StyleComponent': ...

    def set_table_layout(self, value: str) -> 'StyleComponent': ...

    def set_text_align(self, value: str) -> 'StyleComponent': ...

    def set_text_align_all(self, value: str) -> 'StyleComponent': ...

    def set_text_align_last(self, value: str) -> 'StyleComponent': ...

    def set_text_anchor(self, value: str) -> 'StyleComponent': ...

    def set_text_combine_upright(self, value: str) -> 'StyleComponent': ...

    def set_text_decoration(self, value: str) -> 'StyleComponent': ...

    def set_text_decoration_color(self, value: str) -> 'StyleComponent': ...

    def set_text_decoration_line(self, value: str) -> 'StyleComponent': ...

    def set_text_decoration_style(self, value: str) -> 'StyleComponent': ...

    def set_text_decoration_skip(self, value: str) -> 'StyleComponent': ...

    def set_text_emphasis(self, value: str) -> 'StyleComponent': ...

    def set_text_emphasis_color(self, value: str) -> 'StyleComponent': ...

    def set_text_emphasis_style(self, value: str) -> 'StyleComponent': ...

    def set_text_emphasis_position(self, value: str) -> 'StyleComponent': ...

    def set_text_emphasis_skip(self, value: str) -> 'StyleComponent': ...

    def set_text_height(self, value: str) -> 'StyleComponent': ...

    def set_text_indent(self, value: str) -> 'StyleComponent': ...

    def set_text_justify(self, value: str) -> 'StyleComponent': ...

    def set_text_orientation(self, value: str) -> 'StyleComponent': ...

    def set_text_overflow(self, value: str) -> 'StyleComponent': ...

    def set_text_rendering(self, value: str) -> 'StyleComponent': ...

    def set_text_shadow(self, value: str) -> 'StyleComponent': ...

    def set_text_size_adjust(self, value: str) -> 'StyleComponent': ...

    def set_text_space_collapse(self, value: str) -> 'StyleComponent': ...

    def set_text_spacing(self, value: str) -> 'StyleComponent': ...

    def set_text_transform(self, value: str) -> 'StyleComponent': ...

    def set_text_underline_position(self, value: str) -> 'StyleComponent': ...

    def set_text_wrap(self, value: str) -> 'StyleComponent': ...

    def set_top(self, value: str) -> 'StyleComponent': ...

    def set_touch_action(self, value: str) -> 'StyleComponent': ...

    def set_transform(self, value: str) -> 'StyleComponent': ...

    def set_transform_box(self, value: str) -> 'StyleComponent': ...

    def set_transform_origin(self, value: str) -> 'StyleComponent': ...

    def set_transform_style(self, value: str) -> 'StyleComponent': ...

    def set_transition(self, value: str) -> 'StyleComponent': ...

    def set_transition_delay(self, value: str) -> 'StyleComponent': ...

    def set_transition_duration(self, value: str) -> 'StyleComponent': ...

    def set_transition_property(self, value: str) -> 'StyleComponent': ...

    def set_unicode_bidi(self, value: str) -> 'StyleComponent': ...

    def set_vector_effect(self, value: str) -> 'StyleComponent': ...

    def set_vertical_align(self, value: str) -> 'StyleComponent': ...

    def set_visibility(self, value: str) -> 'StyleComponent': ...

    def set_voice_balance(self, value: str) -> 'StyleComponent': ...

    def set_voice_duration(self, value: str) -> 'StyleComponent': ...

    def set_voice_family(self, value: str) -> 'StyleComponent': ...

    def set_voice_pitch(self, value: str) -> 'StyleComponent': ...

    def set_voice_range(self, value: str) -> 'StyleComponent': ...

    def set_voice_rate(self, value: str) -> 'StyleComponent': ...

    def set_voice_stress(self, value: str) -> 'StyleComponent': ...

    def set_voice_volumn(self, value: str) -> 'StyleComponent': ...

    def set_volume(self, value: str) -> 'StyleComponent': ...

    def set_white_space(self, value: str) -> 'StyleComponent': ...

    def set_widows(self, value: str) -> 'StyleComponent': ...

    def set_width(self, value: str) -> 'StyleComponent': ...

    def set_will_change(self, value: str) -> 'StyleComponent': ...

    def set_word_break(self, value: str) -> 'StyleComponent': ...

    def set_word_spacing(self, value: str) -> 'StyleComponent': ...

    def set_word_wrap(self, value: str) -> 'StyleComponent': ...

    def set_wrap_flow(self, value: str) -> 'StyleComponent': ...

    def set_wrap_through(self, value: str) -> 'StyleComponent': ...

    def set_writing_mode(self, value: str) -> 'StyleComponent': ...

    def set_z_index(self, value: str) -> 'StyleComponent': ...

    def set_transition_timing_function(self, value: str) -> 'StyleComponent': ...

